ROM0:0000 3C               inc  a
ROM0:0001 C9               ret  
ROM0:0002 00               nop  
ROM0:0003 00               nop  
ROM0:0004 00               nop  
ROM0:0005 00               nop  
ROM0:0006 00               nop  
ROM0:0007 00               nop  
ROM0:0008 3C               inc  a
ROM0:0009 C9               ret  
ROM0:000A 00               nop  
ROM0:000B 00               nop  
ROM0:000C 00               nop  
ROM0:000D 00               nop  
ROM0:000E 00               nop  
ROM0:000F 00               nop  
ROM0:0010 3C               inc  a
ROM0:0011 C9               ret  
ROM0:0012 00               nop  
ROM0:0013 00               nop  
ROM0:0014 00               nop  
ROM0:0015 00               nop  
ROM0:0016 00               nop  
ROM0:0017 00               nop  
ROM0:0018 3C               inc  a
ROM0:0019 C9               ret  
ROM0:001A 00               nop  
ROM0:001B 00               nop  
ROM0:001C 00               nop  
ROM0:001D 00               nop  
ROM0:001E 00               nop  
ROM0:001F 00               nop  
ROM0:0020 3C               inc  a
ROM0:0021 C9               ret  
ROM0:0022 00               nop  
ROM0:0023 00               nop  
ROM0:0024 00               nop  
ROM0:0025 00               nop  
ROM0:0026 00               nop  
ROM0:0027 00               nop  
ROM0:0028 3C               inc  a
ROM0:0029 C9               ret  
ROM0:002A 00               nop  
ROM0:002B 00               nop  
ROM0:002C 00               nop  
ROM0:002D 00               nop  
ROM0:002E 00               nop  
ROM0:002F 00               nop  
ROM0:0030 3C               inc  a
ROM0:0031 C9               ret  
ROM0:0032 00               nop  
ROM0:0033 00               nop  
ROM0:0034 00               nop  
ROM0:0035 00               nop  
ROM0:0036 00               nop  
ROM0:0037 00               nop  
ROM0:0038 3C               inc  a
ROM0:0039 C9               ret  
ROM0:003A 00               nop  
ROM0:003B 00               nop  
ROM0:003C 00               nop  
ROM0:003D 00               nop  
ROM0:003E 00               nop  
ROM0:003F 00               nop  
ROM0:0040 3C               inc  a
ROM0:0041 C9               ret  
ROM0:0042 00               nop  
ROM0:0043 00               nop  
ROM0:0044 00               nop  
ROM0:0045 00               nop  
ROM0:0046 00               nop  
ROM0:0047 00               nop  
ROM0:0048 3C               inc  a
ROM0:0049 C9               ret  
ROM0:004A 00               nop  
ROM0:004B 00               nop  
ROM0:004C 00               nop  
ROM0:004D 00               nop  
ROM0:004E 00               nop  
ROM0:004F 00               nop  
ROM0:0050 3C               inc  a
ROM0:0051 C9               ret  
ROM0:0052 00               nop  
ROM0:0053 00               nop  
ROM0:0054 00               nop  
ROM0:0055 00               nop  
ROM0:0056 00               nop  
ROM0:0057 00               nop  
ROM0:0058 3C               inc  a
ROM0:0059 C9               ret  
ROM0:005A 00               nop  
ROM0:005B 00               nop  
ROM0:005C 00               nop  
ROM0:005D 00               nop  
ROM0:005E 00               nop  
ROM0:005F 00               nop  
ROM0:0060 00               nop  
ROM0:0061 00               nop  
ROM0:0062 00               nop  
ROM0:0063 00               nop  
ROM0:0064 00               nop  
ROM0:0065 00               nop  
ROM0:0066 00               nop  
ROM0:0067 00               nop  
ROM0:0068 00               nop  
ROM0:0069 00               nop  
ROM0:006A 00               nop  
ROM0:006B 00               nop  
ROM0:006C 00               nop  
ROM0:006D 00               nop  
ROM0:006E 00               nop  
ROM0:006F 00               nop  
ROM0:0070 00               nop  
ROM0:0071 00               nop  
ROM0:0072 00               nop  
ROM0:0073 00               nop  
ROM0:0074 00               nop  
ROM0:0075 00               nop  
ROM0:0076 00               nop  
ROM0:0077 00               nop  
ROM0:0078 00               nop  
ROM0:0079 00               nop  
ROM0:007A 00               nop  
ROM0:007B 00               nop  
ROM0:007C 00               nop  
ROM0:007D 00               nop  
ROM0:007E 00               nop  
ROM0:007F 00               nop  
ROM0:0080 00               nop  
ROM0:0081 00               nop  
ROM0:0082 00               nop  
ROM0:0083 00               nop  
ROM0:0084 00               nop  
ROM0:0085 00               nop  
ROM0:0086 00               nop  
ROM0:0087 00               nop  
ROM0:0088 00               nop  
ROM0:0089 00               nop  
ROM0:008A 00               nop  
ROM0:008B 00               nop  
ROM0:008C 00               nop  
ROM0:008D 00               nop  
ROM0:008E 00               nop  
ROM0:008F 00               nop  
ROM0:0090 00               nop  
ROM0:0091 00               nop  
ROM0:0092 00               nop  
ROM0:0093 00               nop  
ROM0:0094 00               nop  
ROM0:0095 00               nop  
ROM0:0096 00               nop  
ROM0:0097 00               nop  
ROM0:0098 00               nop  
ROM0:0099 00               nop  
ROM0:009A 00               nop  
ROM0:009B 00               nop  
ROM0:009C 00               nop  
ROM0:009D 00               nop  
ROM0:009E 00               nop  
ROM0:009F 00               nop  
ROM0:00A0 00               nop  
ROM0:00A1 00               nop  
ROM0:00A2 00               nop  
ROM0:00A3 00               nop  
ROM0:00A4 00               nop  
ROM0:00A5 00               nop  
ROM0:00A6 00               nop  
ROM0:00A7 00               nop  
ROM0:00A8 00               nop  
ROM0:00A9 00               nop  
ROM0:00AA 00               nop  
ROM0:00AB 00               nop  
ROM0:00AC 00               nop  
ROM0:00AD 00               nop  
ROM0:00AE 00               nop  
ROM0:00AF 00               nop  
ROM0:00B0 00               nop  
ROM0:00B1 00               nop  
ROM0:00B2 00               nop  
ROM0:00B3 00               nop  
ROM0:00B4 00               nop  
ROM0:00B5 00               nop  
ROM0:00B6 00               nop  
ROM0:00B7 00               nop  
ROM0:00B8 00               nop  
ROM0:00B9 00               nop  
ROM0:00BA 00               nop  
ROM0:00BB 00               nop  
ROM0:00BC 00               nop  
ROM0:00BD 00               nop  
ROM0:00BE 00               nop  
ROM0:00BF 00               nop  
ROM0:00C0 00               nop  
ROM0:00C1 00               nop  
ROM0:00C2 00               nop  
ROM0:00C3 00               nop  
ROM0:00C4 00               nop  
ROM0:00C5 00               nop  
ROM0:00C6 00               nop  
ROM0:00C7 00               nop  
ROM0:00C8 00               nop  
ROM0:00C9 00               nop  
ROM0:00CA 00               nop  
ROM0:00CB 00               nop  
ROM0:00CC 00               nop  
ROM0:00CD 00               nop  
ROM0:00CE 00               nop  
ROM0:00CF 00               nop  
ROM0:00D0 00               nop  
ROM0:00D1 00               nop  
ROM0:00D2 00               nop  
ROM0:00D3 00               nop  
ROM0:00D4 00               nop  
ROM0:00D5 00               nop  
ROM0:00D6 00               nop  
ROM0:00D7 00               nop  
ROM0:00D8 00               nop  
ROM0:00D9 00               nop  
ROM0:00DA 00               nop  
ROM0:00DB 00               nop  
ROM0:00DC 00               nop  
ROM0:00DD 00               nop  
ROM0:00DE 00               nop  
ROM0:00DF 00               nop  
ROM0:00E0 00               nop  
ROM0:00E1 00               nop  
ROM0:00E2 00               nop  
ROM0:00E3 00               nop  
ROM0:00E4 00               nop  
ROM0:00E5 00               nop  
ROM0:00E6 00               nop  
ROM0:00E7 00               nop  
ROM0:00E8 00               nop  
ROM0:00E9 00               nop  
ROM0:00EA 00               nop  
ROM0:00EB 00               nop  
ROM0:00EC 00               nop  
ROM0:00ED 00               nop  
ROM0:00EE 00               nop  
ROM0:00EF 00               nop  
ROM0:00F0 00               nop  
ROM0:00F1 00               nop  
ROM0:00F2 00               nop  
ROM0:00F3 00               nop  
ROM0:00F4 00               nop  
ROM0:00F5 00               nop  
ROM0:00F6 00               nop  
ROM0:00F7 00               nop  
ROM0:00F8 00               nop  
ROM0:00F9 00               nop  
ROM0:00FA 00               nop  
ROM0:00FB 00               nop  
ROM0:00FC 00               nop  
ROM0:00FD 00               nop  
ROM0:00FE 00               nop  
ROM0:00FF 00               nop  
ROM0:0100 00               nop  
ROM0:0101 C3 37 06         jp   0637
ROM0:0104 CE ED 66 66+     db   CE,ED,66,66,CC,0D,00,0B,03,73,00,83,00,0C,00,0D
ROM0:0114 00 08 11 1F+     db   00,08,11,1F,88,89,00,0E,DC,CC,6E,E6,DD,DD,D9,99
ROM0:0124 BB BB 67 63+     db   BB,BB,67,63,6E,0E,EC,CC,DD,DC,99,9F,BB,B9,33,3E
ROM0:0134 43 50 55 5F+     db   "CPU_INSTRS     "
ROM0:0143 80               db   80
ROM0:0144 00 00            db   00,00
ROM0:0146 00               db   00
ROM0:0147 01               db   01
ROM0:0148 01               db   01
ROM0:0149 00               db   00
ROM0:014A 00               db   00
ROM0:014B 00               db   00
ROM0:014C 00               db   00
ROM0:014D 3B               db   3B
ROM0:014E F5 30            db   F5,30
ROM0:0150 00               nop  
ROM0:0151 00               nop  
ROM0:0152 00               nop  
ROM0:0153 00               nop  
ROM0:0154 00               nop  
ROM0:0155 00               nop  
ROM0:0156 00               nop  
ROM0:0157 00               nop  
ROM0:0158 00               nop  
ROM0:0159 00               nop  
ROM0:015A 00               nop  
ROM0:015B 00               nop  
ROM0:015C 00               nop  
ROM0:015D 00               nop  
ROM0:015E 00               nop  
ROM0:015F 00               nop  
ROM0:0160 00               nop  
ROM0:0161 00               nop  
ROM0:0162 00               nop  
ROM0:0163 00               nop  
ROM0:0164 00               nop  
ROM0:0165 00               nop  
ROM0:0166 00               nop  
ROM0:0167 00               nop  
ROM0:0168 00               nop  
ROM0:0169 00               nop  
ROM0:016A 00               nop  
ROM0:016B 00               nop  
ROM0:016C 00               nop  
ROM0:016D 00               nop  
ROM0:016E 00               nop  
ROM0:016F 00               nop  
ROM0:0170 00               nop  
ROM0:0171 00               nop  
ROM0:0172 00               nop  
ROM0:0173 00               nop  
ROM0:0174 00               nop  
ROM0:0175 00               nop  
ROM0:0176 00               nop  
ROM0:0177 00               nop  
ROM0:0178 00               nop  
ROM0:0179 00               nop  
ROM0:017A 00               nop  
ROM0:017B 00               nop  
ROM0:017C 00               nop  
ROM0:017D 00               nop  
ROM0:017E 00               nop  
ROM0:017F 00               nop  
ROM0:0180 00               nop  
ROM0:0181 00               nop  
ROM0:0182 00               nop  
ROM0:0183 00               nop  
ROM0:0184 00               nop  
ROM0:0185 00               nop  
ROM0:0186 00               nop  
ROM0:0187 00               nop  
ROM0:0188 00               nop  
ROM0:0189 00               nop  
ROM0:018A 00               nop  
ROM0:018B 00               nop  
ROM0:018C 00               nop  
ROM0:018D 00               nop  
ROM0:018E 00               nop  
ROM0:018F 00               nop  
ROM0:0190 00               nop  
ROM0:0191 00               nop  
ROM0:0192 00               nop  
ROM0:0193 00               nop  
ROM0:0194 00               nop  
ROM0:0195 00               nop  
ROM0:0196 00               nop  
ROM0:0197 00               nop  
ROM0:0198 00               nop  
ROM0:0199 00               nop  
ROM0:019A 00               nop  
ROM0:019B 00               nop  
ROM0:019C 00               nop  
ROM0:019D 00               nop  
ROM0:019E 00               nop  
ROM0:019F 00               nop  
ROM0:01A0 00               nop  
ROM0:01A1 00               nop  
ROM0:01A2 00               nop  
ROM0:01A3 00               nop  
ROM0:01A4 00               nop  
ROM0:01A5 00               nop  
ROM0:01A6 00               nop  
ROM0:01A7 00               nop  
ROM0:01A8 00               nop  
ROM0:01A9 00               nop  
ROM0:01AA 00               nop  
ROM0:01AB 00               nop  
ROM0:01AC 00               nop  
ROM0:01AD 00               nop  
ROM0:01AE 00               nop  
ROM0:01AF 00               nop  
ROM0:01B0 00               nop  
ROM0:01B1 00               nop  
ROM0:01B2 00               nop  
ROM0:01B3 00               nop  
ROM0:01B4 00               nop  
ROM0:01B5 00               nop  
ROM0:01B6 00               nop  
ROM0:01B7 00               nop  
ROM0:01B8 00               nop  
ROM0:01B9 00               nop  
ROM0:01BA 00               nop  
ROM0:01BB 00               nop  
ROM0:01BC 00               nop  
ROM0:01BD 00               nop  
ROM0:01BE 00               nop  
ROM0:01BF 00               nop  
ROM0:01C0 00               nop  
ROM0:01C1 00               nop  
ROM0:01C2 00               nop  
ROM0:01C3 00               nop  
ROM0:01C4 00               nop  
ROM0:01C5 00               nop  
ROM0:01C6 00               nop  
ROM0:01C7 00               nop  
ROM0:01C8 00               nop  
ROM0:01C9 00               nop  
ROM0:01CA 00               nop  
ROM0:01CB 00               nop  
ROM0:01CC 00               nop  
ROM0:01CD 00               nop  
ROM0:01CE 00               nop  
ROM0:01CF 00               nop  
ROM0:01D0 00               nop  
ROM0:01D1 00               nop  
ROM0:01D2 00               nop  
ROM0:01D3 00               nop  
ROM0:01D4 00               nop  
ROM0:01D5 00               nop  
ROM0:01D6 00               nop  
ROM0:01D7 00               nop  
ROM0:01D8 00               nop  
ROM0:01D9 00               nop  
ROM0:01DA 00               nop  
ROM0:01DB 00               nop  
ROM0:01DC 00               nop  
ROM0:01DD 00               nop  
ROM0:01DE 00               nop  
ROM0:01DF 00               nop  
ROM0:01E0 00               nop  
ROM0:01E1 00               nop  
ROM0:01E2 00               nop  
ROM0:01E3 00               nop  
ROM0:01E4 00               nop  
ROM0:01E5 00               nop  
ROM0:01E6 00               nop  
ROM0:01E7 00               nop  
ROM0:01E8 00               nop  
ROM0:01E9 00               nop  
ROM0:01EA 00               nop  
ROM0:01EB 00               nop  
ROM0:01EC 00               nop  
ROM0:01ED 00               nop  
ROM0:01EE 00               nop  
ROM0:01EF 00               nop  
ROM0:01F0 00               nop  
ROM0:01F1 00               nop  
ROM0:01F2 00               nop  
ROM0:01F3 00               nop  
ROM0:01F4 00               nop  
ROM0:01F5 00               nop  
ROM0:01F6 00               nop  
ROM0:01F7 00               nop  
ROM0:01F8 00               nop  
ROM0:01F9 00               nop  
ROM0:01FA 00               nop  
ROM0:01FB 00               nop  
ROM0:01FC 00               nop  
ROM0:01FD 00               nop  
ROM0:01FE 00               nop  
ROM0:01FF 00               nop  
ROM0:0200 47               ld   b,a
ROM0:0201 11 00 C0         ld   de,C000
ROM0:0204 0E 10            ld   c,10
ROM0:0206 2A               ldi  a,(hl)
ROM0:0207 12               ld   (de),a
ROM0:0208 1C               inc  e
ROM0:0209 20 FB            jr   nz,0206
ROM0:020B 14               inc  d
ROM0:020C 0D               dec  c
ROM0:020D 20 F7            jr   nz,0206
ROM0:020F 78               ld   a,b
ROM0:0210 C3 00 C0         jp   C000
ROM0:0213 D6 05            sub  a,05
ROM0:0215 30 FC            jr   nc,0213
ROM0:0217 1F               rra  
ROM0:0218 30 00            jr   nc,021A
ROM0:021A CE 01            adc  a,01
ROM0:021C D0               ret  nc
ROM0:021D C8               ret  z
ROM0:021E 00               nop  
ROM0:021F C9               ret  
ROM0:0220 B7               or   a
ROM0:0221 C8               ret  z
ROM0:0222 F5               push af
ROM0:0223 3E DF            ld   a,DF
ROM0:0225 CD 13 02         call 0213
ROM0:0228 F1               pop  af
ROM0:0229 3D               dec  a
ROM0:022A 20 F6            jr   nz,0222
ROM0:022C C9               ret  
ROM0:022D B7               or   a
ROM0:022E C8               ret  z
ROM0:022F F5               push af
ROM0:0230 3E FF            ld   a,FF
ROM0:0232 CD 22 02         call 0222
ROM0:0235 3E D4            ld   a,D4
ROM0:0237 CD 13 02         call 0213
ROM0:023A F1               pop  af
ROM0:023B 3D               dec  a
ROM0:023C 20 F1            jr   nz,022F
ROM0:023E C9               ret  
ROM0:023F F5               push af
ROM0:0240 7C               ld   a,h
ROM0:0241 CD 20 02         call 0220
ROM0:0244 7D               ld   a,l
ROM0:0245 CD 13 02         call 0213
ROM0:0248 F1               pop  af
ROM0:0249 C9               ret  
ROM0:024A 00               nop  
ROM0:024B 00               nop  
ROM0:024C 00               nop  
ROM0:024D 00               nop  
ROM0:024E 00               nop  
ROM0:024F 00               nop  
ROM0:0250 00               nop  
ROM0:0251 00               nop  
ROM0:0252 00               nop  
ROM0:0253 00               nop  
ROM0:0254 00               nop  
ROM0:0255 00               nop  
ROM0:0256 00               nop  
ROM0:0257 00               nop  
ROM0:0258 00               nop  
ROM0:0259 00               nop  
ROM0:025A 00               nop  
ROM0:025B 00               nop  
ROM0:025C C9               ret  
ROM0:025D 18 00            jr   025F
ROM0:025F 3E FF            ld   a,FF
ROM0:0261 E0 C0            ld   (ff00+C0),a
ROM0:0263 E0 C1            ld   (ff00+C1),a
ROM0:0265 E0 C2            ld   (ff00+C2),a
ROM0:0267 E0 C3            ld   (ff00+C3),a
ROM0:0269 C9               ret  
ROM0:026A F5               push af
ROM0:026B C5               push bc
ROM0:026C D5               push de
ROM0:026D E5               push hl
ROM0:026E 21 C3 FF         ld   hl,FFC3
ROM0:0271 46               ld   b,(hl)
